apiVersion: apps/v1
kind: Deployment
metadata:
  name: comunicacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comunicacao
  template:
    metadata:
      labels:
        app: comunicacao
    spec:
      containers:
        - name: comunicacao
          image: seu-registro/comunicacao:latest
          ports:
            - containerPort: 3004
          envFrom:
            - secretRef:
                name: comunicacao-env
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
