apiVersion: apps/v1
kind: Deployment
metadata:
  name: empresas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: empresas
  template:
    metadata:
      labels:
        app: empresas
    spec:
      containers:
        - name: empresas
          image: seu-registro/empresas:latest
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: empresas-env
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
