apiVersion: apps/v1
kind: Deployment
metadata:
  name: automacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: automacao
  template:
    metadata:
      labels:
        app: automacao
    spec:
      containers:
        - name: automacao
          image: seu-registro/automacao:latest
          ports:
            - containerPort: 3006
          envFrom:
            - secretRef:
                name: automacao-env
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
