apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vendas
  template:
    metadata:
      labels:
        app: vendas
    spec:
      containers:
        - name: vendas
          image: seu-registro/vendas:latest
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: vendas-env
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
